services:
  db:
    container_name: "my_finance_db"
    image: postgres:12.5-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_finance_network
    volumes:
      - db:/var/lib/postgres

  # app:
  #   container_name: "my_finance_app"
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     - my_finance_network

networks:
  my_finance_network:
    driver: bridge

volumes:
  db:
  